Use SELECTANY instead of EXTERN_C __declspec(selectany)
src/inc/clrproviders.h:526:32: error: ‘MICROSOFT_WINDOWS_DOTNETRUNTIME_RUNDOWN_PROVIDER_DOTNET_Context’ initialized and declared ‘extern’ [-Werror]